code --install-extension 2gua.rainbow-brackets
code --install-extension alefragnani.numbered-bookmarks
code --install-extension alefragnani.project-manager
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension formulahendry.terminal
code --install-extension gerane.Theme-Dark-Dracula
code --install-extension HookyQR.beautify
code --install-extension infosec-intern.yara
code --install-extension leizongmin.node-module-intellisense
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-python.python
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension oderwat.indent-rainbow
code --install-extension pranaygp.vscode-css-peek
code --install-extension quicktype.quicktype
code --install-extension ritwickdey.LiveServer
code --install-extension robertohuertasm.vscode-icons
code --install-extension Shan.code-settings-sync
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension skyapps.fish-vscode
code --install-extension spywhere.guides
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zhuangtongfa.Material-theme
code --install-extension Zignd.html-css-class-completion
code --install-extension ziyasal.vscode-open-in-github
